version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-project
    env_file:
      - .env.testing
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/0.sql
    ports:
      - 3307:3306
    networks:
      - my-network
    command: --default-authentication-plugin=mysql_native_password

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.testing
    ports:
      - 5001:5000
    networks:
      - my-network
    command: sh -c "pip install pytest==7.3.1 && wait-for-it.sh mysql-project:3306 -t 60 && flask db init && flask db migrate && echo updating && flask db upgrade && python -m pytest -s ./app/tests"

volumes:
  mysql-data:

networks:
  my-network:
